port: 9010
appBase: .
baseDir: .
warName: app
nameSpace: /
systemProperties:
  user.language: es
  user.language.format: AR
  user.country: ARG
  user.country.format: AR
  user.timezone: America/Buenos_Aires